#!/usr/bin/env bash
#
# @category Installation PHPSocket Framework (CentOS 7.x, 8.x)
# @author Андрей Новиков <andrey@novikov.be>
# @data 07/12/2015
#

# Make sure only root can run our script
if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

######## CONFIG ##########################################################################
export vendor=vendor/bermud-ru/phproll
export serverRoot=$(pwd)
export PROJECT=${PWD##*/}
##########################################################################################
printf "Post-install scripting ...\n\n"

printf "NGINX webSocket configuration\n"
cat << EOF > ./etc/nginx/$PROJECT.wss.conf
upstream appserver {
    server 127.0.0.1:8001; # appserver_ip:ws_port
}
server {
    # client_wss_port
    listen 8000;
    ssl on;
    ssl_certificate     $SSL_path/nginx.crt;
    ssl_certificate_key $SSL_path/nginx.key;
    #so_keepalive on;
    tcp_nodelay on;
    #websocket_pass appserver;
    #websocket_buffer 1k;
    location / {
        # prevents 502 bad gateway error
        proxy_buffers 8 32k;
        proxy_buffer_size 64k;
        proxy_pass http://appserver;
        proxy_redirect off;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-NginX-Proxy true;
        # WebSocket support
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_read_timeout 86400;
    }
}
EOF

exit